<?php
/**
 * DriveHR Job Sync Engine Class
 *
 * Shared synchronization engine that stores DriveHR job data as WordPress
 * custom posts and maintains perfect parity by removing jobs no longer in
 * the DriveHR feed. Extracted from the webhook handler (v2.2.0) so both
 * delivery mechanisms — the legacy push webhook and the pull-based feed
 * sync — process jobs through a single, identical code path.
 *
 * @package DriveHR
 * @since 2.2.0
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit('Direct access denied.');
}

/**
 * DriveHR Job Sync Engine
 *
 * Processes a complete job list from DriveHR: creates new jobs, updates
 * existing ones, and removes stale jobs missing from the incoming list.
 * Delivery-mechanism agnostic — callers are responsible for transport,
 * authentication, and payload validation.
 *
 * @since 2.2.0
 */
class DriveHR_Job_Sync {

    /**
     * Maximum jobs allowed per sync to prevent resource exhaustion
     *
     * @since 2.2.0
     */
    public const MAX_JOBS_PER_SYNC = 100;

    /**
     * Maximum accepted length of a job ID
     *
     * Matches the indexed portion of postmeta.meta_value so lookups stay fast
     * and a malicious feed cannot store megabytes per meta row.
     *
     * @since 2.3.0
     */
    private const MAX_ID_LENGTH = 191;

    /**
     * Maximum accepted length of short text fields (title, location, etc.)
     *
     * @since 2.3.0
     */
    private const MAX_TEXT_LENGTH = 500;

    /**
     * Maximum accepted length of a job description in bytes (256 KiB)
     *
     * @since 2.3.0
     */
    private const MAX_DESCRIPTION_LENGTH = 262144;

    /**
     * Characters permitted in a job ID
     *
     * IDs are generated by the scraper as "drivehr-<n>" or a slug; anything
     * outside this set is rejected rather than sanitized so a corrupted feed
     * fails loudly instead of silently re-keying every job.
     *
     * @since 2.3.0
     */
    private const ID_PATTERN = '/^[A-Za-z0-9][A-Za-z0-9._:-]{0,190}$/';

    /**
     * Synchronize a complete job list into WordPress
     *
     * Runs the full parity sync: upserts every incoming job, then removes
     * any WordPress job whose job_id is absent from the incoming list.
     * An empty jobs array therefore removes all jobs — callers must guard
     * against unintended empty payloads upstream.
     *
     * @param array $jobs Complete array of job data from DriveHR
     * @return array Processing results with counts and errors
     * @throws Exception If critical processing error occurs.
     * @since 2.2.0
     */
    public function sync(array $jobs): array {
        $result = $this->process_jobs($jobs);

        // Remove stale jobs that are no longer in DriveHR. Only IDs of jobs
        // that were actually stored count as "current" so a batch of invalid
        // records cannot wipe the existing listings.
        $current_job_ids = $result['stored_job_ids'];
        unset($result['stored_job_ids']);
        $removal_result = $this->remove_stale_jobs($current_job_ids);
        $result['removed'] = $removal_result['removed'];

        return $result;
    }

    /**
     * Process array of jobs from a sync payload
     *
     * Iterates through jobs array and stores each job as a WordPress post
     * with proper error handling and transaction safety.
     *
     * @param array $jobs Array of job data
     * @return array Processing results with counts and errors
     * @throws Exception If critical processing error occurs.
     * @since 2.2.0 Moved from DriveHR_Webhook_Handler::process_jobs()
     */
    private function process_jobs(array $jobs): array {
        global $wpdb;

        $processed = 0;
        $updated = 0;
        $skipped = 0;
        $errors = [];
        $stored_job_ids = [];

        // OPTIMIZATION 1: Increase PHP limits for large batches
        @ini_set('memory_limit', '256M');
        @ini_set('max_execution_time', '120');

        // OPTIMIZATION 2: Bulk lookup existing jobs (single query instead of N queries)
        $existing_jobs_map = $this->bulk_lookup_existing_jobs($jobs);

        // OPTIMIZATION 3: Single batch transaction for all jobs
        $wpdb->query('START TRANSACTION');

        try {
            foreach ($jobs as $index => $job) {
                if (!is_array($job)) {
                    $errors[] = "Job at index {$index}: Invalid job data format";
                    continue;
                }

                try {
                    // Pass existing jobs map to avoid per-job queries
                    $result = $this->store_job($job, $existing_jobs_map);
                    $stored_job_ids[] = $result['job_id'];
                    if ($result['action'] === 'created') {
                        $processed++;
                    } elseif ($result['action'] === 'updated') {
                        $updated++;
                    } else {
                        $skipped++;
                    }
                } catch (Exception $e) {
                    $errors[] = "Job at index {$index}: " . $e->getMessage();
                }
            }

            // Commit all changes as single transaction
            $wpdb->query('COMMIT');

            // Save job count before cleanup (needed for return value)
            $total_jobs = count($jobs);

            // OPTIMIZATION: Resource cleanup to prevent memory leaks
            // This is critical for large batch operations (v1.6.0)
            wp_reset_postdata(); // Clear global post data after wp_insert_post/wp_update_post
            unset($existing_jobs_map, $jobs); // Free large arrays from memory
            if (function_exists('gc_collect_cycles')) {
                gc_collect_cycles(); // Force PHP garbage collection
            }

        } catch (Exception $e) {
            // Rollback all changes on any critical error
            $wpdb->query('ROLLBACK');
            throw $e;
        }

        return [
            'success' => true,
            'processed' => $processed,
            'updated' => $updated,
            'skipped' => $skipped,
            'total' => $total_jobs,
            'errors' => $errors,
            'timestamp' => current_time('c'),
            'source' => 'drivehr-netlify-sync',
            'stored_job_ids' => $stored_job_ids
        ];
    }

    /**
     * Bulk lookup existing jobs by job IDs
     *
     * PERFORMANCE OPTIMIZATION: Single database query to fetch all existing
     * job post IDs instead of individual meta queries per job.
     *
     * @param array $jobs Array of job data
     * @return array Map of job_id => post_id for existing jobs
     * @since 2.2.0 Moved from DriveHR_Webhook_Handler::bulk_lookup_existing_jobs()
     */
    private function bulk_lookup_existing_jobs(array $jobs): array {
        global $wpdb;

        // Extract all scalar job IDs from incoming jobs (invalid records are
        // rejected later by validate_job(); here they simply get no lookup)
        $job_ids = array_values(array_filter(array_map(function($job) {
            $id = is_array($job) ? ($job['id'] ?? null) : null;
            return (is_string($id) || is_int($id)) && (string) $id !== '' ? (string) $id : null;
        }, $jobs)));

        if (empty($job_ids)) {
            return [];
        }

        // Build placeholders for prepared statement
        $placeholders = implode(',', array_fill(0, count($job_ids), '%s'));

        // Single query to fetch all existing job post IDs
        $query = $wpdb->prepare("
            SELECT pm.meta_value as job_id, pm.post_id
            FROM {$wpdb->postmeta} pm
            INNER JOIN {$wpdb->posts} p ON pm.post_id = p.ID
            WHERE pm.meta_key = 'job_id'
            AND pm.meta_value IN ($placeholders)
            AND p.post_type = 'drivehr_job'
            AND p.post_status != 'trash'
        ", $job_ids);

        $results = $wpdb->get_results($query);

        // Build map of job_id => post_id
        $map = [];
        foreach ($results as $row) {
            $map[$row->job_id] = (int)$row->post_id;
        }

        return $map;
    }

    /**
     * Prepare sanitized post data from raw job data
     *
     * Extracts and sanitizes all job fields from the sync payload,
     * handling various field name formats for backward compatibility.
     *
     * @param array $job Raw job data from sync payload
     * @return array Sanitized post data ready for wp_insert_post/wp_update_post
     * @since 2.2.0 Moved from DriveHR_Webhook_Handler::prepare_job_post_data()
     */
    private function prepare_job_post_data(array $job): array {
        return [
            'post_type' => 'drivehr_job',
            'post_title' => $this->text_field($job['title']),
            'post_content' => wp_kses_post($this->string_field($job['description'] ?? '', self::MAX_DESCRIPTION_LENGTH)),
            'post_excerpt' => sanitize_textarea_field($this->string_field($job['summary'] ?? '', self::MAX_TEXT_LENGTH * 4)),
            'post_status' => 'publish',
            'post_author' => 0,
            'post_date' => $this->parse_date($this->text_field($job['postedDate'] ?? $job['posted_date'] ?? '')),
            'meta_input' => $this->prepare_job_meta_data($job)
        ];
    }

    /**
     * Validate a single job record before it touches the database
     *
     * Every job is checked, not just the first one in the batch. Types are
     * enforced because sanitize_text_field() on an array or object emits
     * warnings and stores an empty string, which would silently corrupt data.
     *
     * @since 2.3.0
     * @param mixed $job Decoded job record from the feed or webhook
     * @throws Exception When the record is not an array or has an invalid id/title
     * @return void
     */
    private function validate_job($job): void {
        if (!is_array($job)) {
            throw new Exception('Invalid job data format');
        }

        $id = $job['id'] ?? null;
        if (!is_string($id) && !is_int($id)) {
            throw new Exception('Missing required fields: id and title are required');
        }
        $id = (string) $id;
        if ($id === '' || strlen($id) > self::MAX_ID_LENGTH || !preg_match(self::ID_PATTERN, $id)) {
            throw new Exception('Invalid job id');
        }

        $title = $job['title'] ?? null;
        if (!is_string($title) || trim($title) === '') {
            throw new Exception('Missing required fields: id and title are required');
        }
        if (strlen($title) > self::MAX_TEXT_LENGTH) {
            throw new Exception('Job title exceeds maximum length');
        }

        $description = $job['description'] ?? '';
        if (!is_string($description) || strlen($description) > self::MAX_DESCRIPTION_LENGTH) {
            throw new Exception('Job description is not a string or exceeds maximum length');
        }
    }

    /**
     * Coerce a feed value to a bounded string
     *
     * Non-string scalars are cast; arrays, objects and null become an empty
     * string so nothing unexpected reaches the WordPress sanitizers.
     *
     * @since 2.3.0
     * @param mixed $value Raw value from the feed
     * @param int $max_length Maximum length in bytes; longer values are truncated
     * @return string Bounded string
     */
    private function string_field($value, int $max_length): string {
        if (is_string($value)) {
            $string = $value;
        } elseif (is_int($value) || is_float($value)) {
            $string = (string) $value;
        } else {
            return '';
        }

        return strlen($string) > $max_length ? substr($string, 0, $max_length) : $string;
    }

    /**
     * Sanitize a short single-line text field from the feed
     *
     * @since 2.3.0
     * @param mixed $value Raw value from the feed
     * @return string Sanitized text, at most MAX_TEXT_LENGTH bytes
     */
    private function text_field($value): string {
        return sanitize_text_field($this->string_field($value, self::MAX_TEXT_LENGTH));
    }

    /**
     * Sanitize a URL from the feed, allowing only http(s)
     *
     * esc_url_raw() alone accepts mailto:, tel:, ftp: and other schemes from
     * wp_allowed_protocols(). Apply and source links are rendered as anchors
     * and framed in the apply modal, so anything other than a web URL is
     * dropped rather than stored.
     *
     * @since 2.3.0
     * @param mixed $value Raw value from the feed
     * @return string Sanitized http(s) URL or empty string
     */
    private function http_url_field($value): string {
        $url = esc_url_raw($this->string_field($value, 2048), ['http', 'https']);
        if ($url === '') {
            return '';
        }

        $scheme = wp_parse_url($url, PHP_URL_SCHEME);
        return in_array($scheme, ['http', 'https'], true) ? $url : '';
    }

    /**
     * Prepare sanitized meta data from raw job data
     *
     * Sanitizes all job metadata fields, handling backward compatibility
     * for both camelCase and snake_case field naming conventions.
     *
     * PERFORMANCE OPTIMIZATION: Excludes description from raw_data to reduce
     * database storage size (description is stored in post_content).
     *
     * @param array $job Raw job data from sync payload
     * @return array Sanitized meta data array
     * @since 2.2.0 Moved from DriveHR_Webhook_Handler::prepare_job_meta_data()
     */
    private function prepare_job_meta_data(array $job): array {
        // OPTIMIZATION: Exclude description from raw_data (stored in post_content already)
        $job_meta_copy = $job;
        unset($job_meta_copy['description']);

        // rawData duplicates the scraped fields (including HTML) and is never
        // rendered; keeping it would store unsanitized feed content in postmeta.
        unset($job_meta_copy['rawData'], $job_meta_copy['raw_data']);

        return [
            'job_id' => (string) $job['id'],
            'department' => $this->text_field($job['department'] ?? ''),
            'location' => $this->text_field($job['location'] ?? ''),
            'job_type' => $this->text_field($job['type'] ?? $job['jobType'] ?? ''),
            'employment_type' => $this->text_field($job['employmentType'] ?? ''),
            'salary_range' => $this->text_field($job['salaryRange'] ?? $job['salary_range'] ?? ''),
            'apply_url' => $this->http_url_field($job['applyUrl'] ?? $job['apply_url'] ?? ''),
            'posted_date' => $this->text_field($job['postedDate'] ?? $job['posted_date'] ?? ''),
            'expiry_date' => $this->text_field($job['expiryDate'] ?? $job['expiry_date'] ?? ''),
            'source' => 'drivehr',
            'source_url' => $this->http_url_field($job['sourceUrl'] ?? ''),
            'raw_data' => wp_json_encode($job_meta_copy, JSON_UNESCAPED_UNICODE),
            'last_updated' => current_time('mysql'),
            'sync_version' => DRIVEHR_WEBHOOK_VERSION
        ];
    }

    /**
     * Store or update a single job in WordPress
     *
     * PERFORMANCE OPTIMIZATION: Uses bulk lookup map to avoid per-job queries.
     * Transactions are handled at batch level in process_jobs().
     *
     * @param array $job Job data from sync payload
     * @param array $existing_jobs_map Map of job_id => post_id from bulk lookup
     * @return array Result with action taken and post ID
     * @throws Exception If job storage fails.
     * @since 2.2.0 Moved from DriveHR_Webhook_Handler::store_job()
     */
    private function store_job(array $job, array $existing_jobs_map = []): array {
        // Validate types, required fields and size limits (throws on failure)
        $this->validate_job($job);
        $job['id'] = (string) $job['id'];

        // OPTIMIZATION: Check existing job from bulk lookup map (no query needed)
        $existing_post_id = $existing_jobs_map[$job['id']] ?? null;

        // Prepare sanitized job data
        $post_data = $this->prepare_job_post_data($job);

        $action = 'created';

        if ($existing_post_id) {
            // Fire before update action
            do_action('drivehr_before_job_update', $job);

            // Update existing job
            $post_data['ID'] = $existing_post_id;
            $result = wp_update_post($post_data, true);
            $action = 'updated';
        } else {
            // Fire before insert action
            do_action('drivehr_before_job_insert', $job);

            // Create new job
            $result = wp_insert_post($post_data, true);
            $action = 'created';
        }

        // Check for WordPress errors
        if (is_wp_error($result)) {
            throw new Exception('WordPress error: ' . $result->get_error_message());
        }

        return [
            'action' => $action,
            'post_id' => $result,
            'job_id' => $job['id']
        ];
    }

    /**
     * Remove stale jobs that are no longer in DriveHR
     *
     * Compares current job IDs from DriveHR with existing jobs in WordPress
     * and removes any jobs that are no longer present in the DriveHR feed.
     * This maintains perfect parity between DriveHR and WordPress job listings.
     *
     * PERFORMANCE OPTIMIZATION (v1.6.0): Uses single bulk query instead of N+1
     * pattern. For 100 jobs: 1 query vs 101 queries (90% reduction).
     *
     * @param array $current_job_ids Array of job IDs currently in DriveHR
     * @return array Result with count of removed jobs
     * @throws Exception If job removal fails.
     * @since 2.2.0 Moved from DriveHR_Webhook_Handler::remove_stale_jobs()
     */
    private function remove_stale_jobs(array $current_job_ids): array {
        global $wpdb;

        // Start database transaction for atomicity
        $wpdb->query('START TRANSACTION');

        try {
            // OPTIMIZATION: Single query to get all existing jobs with their job_id meta
            // Replaces N+1 query pattern (1 get_posts query + N get_post_meta calls)
            $query = "
                SELECT p.ID as post_id, pm.meta_value as job_id
                FROM {$wpdb->posts} p
                INNER JOIN {$wpdb->postmeta} pm ON p.ID = pm.post_id
                WHERE p.post_type = 'drivehr_job'
                AND p.post_status != 'trash'
                AND pm.meta_key = 'job_id'
            ";

            $existing_jobs = $wpdb->get_results($query);

            $removed = 0;
            $removed_job_ids = [];

            foreach ($existing_jobs as $job) {
                // If this job is not in the current DriveHR list, remove it
                if (!in_array($job->job_id, $current_job_ids, true)) {
                    // Fire before delete action for integrations
                    do_action('drivehr_before_job_delete', $job->post_id, $job->job_id);

                    // Permanently delete the job (bypass trash)
                    $delete_result = wp_delete_post($job->post_id, true);

                    if ($delete_result) {
                        $removed++;
                        $removed_job_ids[] = $job->job_id;

                        // Fire after delete action for integrations
                        do_action('drivehr_after_job_delete', $job->post_id, $job->job_id);
                    }
                }
            }

            // Commit transaction
            $wpdb->query('COMMIT');

            // Log removal activity
            if ($removed > 0) {
                $this->log_sync_activity(
                    "Removed {$removed} stale jobs",
                    ['removed_job_ids' => $removed_job_ids]
                );
            }

            return [
                'removed' => $removed,
                'removed_job_ids' => $removed_job_ids
            ];

        } catch (Exception $e) {
            // Rollback transaction on any error
            $wpdb->query('ROLLBACK');
            throw new Exception('Failed to remove stale jobs: ' . $e->getMessage());
        }
    }

    /**
     * Parse date string to WordPress format
     *
     * Converts various date formats to WordPress-compatible MySQL datetime format.
     * Uses gmdate() for timezone consistency as recommended by WordPress standards.
     *
     * @param string $date_string Date in various formats
     * @return string WordPress-compatible date string in GMT
     * @since 2.2.0 Moved from DriveHR_Webhook_Handler::parse_date()
     */
    private function parse_date(string $date_string): string {
        if (empty($date_string)) {
            return current_time('mysql', true);
        }

        // Try to parse the date
        $timestamp = strtotime($date_string);
        if ($timestamp === false) {
            // If parsing fails, use current time
            return current_time('mysql', true);
        }

        return gmdate('Y-m-d H:i:s', $timestamp);
    }

    /**
     * Log sync activity for debugging
     *
     * Only logs when WP_DEBUG is enabled to avoid performance impact
     * in production environments.
     *
     * @param string $message Log message
     * @param mixed $data Additional data to log
     * @return void
     * @since 2.2.0
     */
    private function log_sync_activity(string $message, $data = null): void {
        if (!defined('WP_DEBUG') || !WP_DEBUG) {
            return;
        }

        $log_entry = '[DriveHR Job Sync] ' . $message;
        if ($data !== null) {
            $log_entry .= ' | Data: ' . wp_json_encode($data, JSON_UNESCAPED_UNICODE);
        }

        error_log($log_entry);
    }
}
